<?php
declare(strict_types=1);

// HubspotDataStudio SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

HubspotDataStudioUtility::setRegistrar(function (HubspotDataStudioUtility $u): void {
    $u->clean = [HubspotDataStudioClean::class, 'call'];
    $u->done = [HubspotDataStudioDone::class, 'call'];
    $u->make_error = [HubspotDataStudioMakeError::class, 'call'];
    $u->feature_add = [HubspotDataStudioFeatureAdd::class, 'call'];
    $u->feature_hook = [HubspotDataStudioFeatureHook::class, 'call'];
    $u->feature_init = [HubspotDataStudioFeatureInit::class, 'call'];
    $u->fetcher = [HubspotDataStudioFetcher::class, 'call'];
    $u->make_fetch_def = [HubspotDataStudioMakeFetchDef::class, 'call'];
    $u->make_context = [HubspotDataStudioMakeContext::class, 'call'];
    $u->make_options = [HubspotDataStudioMakeOptions::class, 'call'];
    $u->make_request = [HubspotDataStudioMakeRequest::class, 'call'];
    $u->make_response = [HubspotDataStudioMakeResponse::class, 'call'];
    $u->make_result = [HubspotDataStudioMakeResult::class, 'call'];
    $u->make_point = [HubspotDataStudioMakePoint::class, 'call'];
    $u->make_spec = [HubspotDataStudioMakeSpec::class, 'call'];
    $u->make_url = [HubspotDataStudioMakeUrl::class, 'call'];
    $u->param = [HubspotDataStudioParam::class, 'call'];
    $u->prepare_auth = [HubspotDataStudioPrepareAuth::class, 'call'];
    $u->prepare_body = [HubspotDataStudioPrepareBody::class, 'call'];
    $u->prepare_headers = [HubspotDataStudioPrepareHeaders::class, 'call'];
    $u->prepare_method = [HubspotDataStudioPrepareMethod::class, 'call'];
    $u->prepare_params = [HubspotDataStudioPrepareParams::class, 'call'];
    $u->prepare_path = [HubspotDataStudioPreparePath::class, 'call'];
    $u->prepare_query = [HubspotDataStudioPrepareQuery::class, 'call'];
    $u->graphql_body = [HubspotDataStudioGraphql::class, 'body'];
    $u->graphql_errors = [HubspotDataStudioGraphql::class, 'errors'];
    $u->result_basic = [HubspotDataStudioResultBasic::class, 'call'];
    $u->result_body = [HubspotDataStudioResultBody::class, 'call'];
    $u->result_headers = [HubspotDataStudioResultHeaders::class, 'call'];
    $u->transform_request = [HubspotDataStudioTransformRequest::class, 'call'];
    $u->transform_response = [HubspotDataStudioTransformResponse::class, 'call'];
});
